namespace MailChimp.Api.Net.Enum
{
    public enum SubTargetType
    {
        not_applicable,
        advice,
        click_details,
        domain_performance,
        eepurl,
        email_activity,
        locations,
        sent_to,
        sub_reports,
        unsubscribed,
        action1,
        action2,
        action3,
        action4,
        action5,
        action6,
        members,
        feedback,
        messages,
        emails,
        queue,
        abuse_reports,
        activity,
        clients,
        growth_history,
        interest_categories,
        interests,
        merge_fields,
        segments,
        goals,
        notes,
        removed_subscribers,
        content,
        send_checklist,
        schedule

    }
}
